import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script'; // ✅ Ye zaruri hai!
import './globals.css';
import Header from '@/Components/Header';
import Footer from '@/Components/Footer';
import { FilterProvider } from '@/Context/FilterProducts';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FilterProvider>
          <Header />
          {children}
          <Footer />
        </FilterProvider>

        {/* ✅ Tawk.io script code */}
        <Script id='tawkto-chat' strategy='afterInteractive'>
          {`
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/68e53df7b52c08194e79c20a/1j6vnk47d';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `}
        </Script>
      </body>
    </html>
  );
}
