// products.js

const RecentProducts = [
  {
    id: 1,
    image: '/Images/Product1.jpg',
    alt: 'Handfree',
    title: 'Wired Handfree',
    desc: 'High-quality wired handfree for daily use',
    slug: 'wired-handfree',
    longDesc:
      'Experience crystal clear sound with durable wired handfree, perfect for music and calls.',
    price: 1200,
    category: 'Headphone',
  },
  {
    id: 2,
    image: '/Images/Product2.jpg',
    alt: 'Headphone',
    title: 'Over-Ear Headphone',
    desc: 'Comfortable over-ear headphone',
    slug: 'over-ear-headphone',
    longDesc:
      'Premium sound quality with noise isolation and cushioned ear pads for long sessions.',
    price: 3500,
    category: 'Headphone',
  },
  {
    id: 3,
    image: '/Images/Product3.webp',
    alt: 'Earbuds',
    title: 'Wireless Earbuds',
    desc: 'Bluetooth wireless earbuds',
    slug: 'wireless-earbuds',
    longDesc:
      'Lightweight and powerful earbuds with long battery life and seamless Bluetooth pairing.',
    price: 2800,
    category: 'Headphone',
  },
  {
    id: 4,
    image: '/Images/Product4.avif',
    alt: 'PS4 Remote',
    title: 'PS4 Remote Controller',
    desc: 'Wireless controller for PS4',
    slug: 'ps4-remote-controller',
    longDesc:
      'Responsive and ergonomic PS4 remote controller with vibration feedback.',
    price: 5000,
    category: 'Gaming',
  },
];

const FeatureProducts = [
  {
    id: 6,
    image: '/Images/Product5.jpg',
    alt: 'Smartwatch',
    title: 'Smartwatch Series 5',
    desc: 'Fitness and lifestyle smartwatch',
    slug: 'smartwatch-series-5',
    longDesc:
      'Track fitness, monitor health, and stay connected with a stylish smartwatch.',
    price: 7500,
    category: 'Smartwatch',
  },
  {
    id: 7,
    image: '/Images/Product6.webp',
    alt: 'Bluetooth Speaker',
    title: 'Portable Bluetooth Speaker',
    desc: 'Loud and clear portable speaker',
    slug: 'portable-bluetooth-speaker',
    longDesc:
      'Compact design with booming sound and water resistance, perfect for travel.',
    price: 3000,
    category: 'Speaker',
  },
  {
    id: 8,
    image: '/Images/Product7.webp',
    alt: 'Gaming Mouse',
    title: 'RGB Gaming Mouse',
    desc: 'High precision mouse',
    slug: 'rgb-gaming-mouse',
    longDesc:
      'Ergonomic gaming mouse with RGB lighting and multiple DPI settings.',
    price: 2200,
    category: 'Gaming',
  },
  {
    id: 9,
    image: '/Images/Product8.jpg',
    alt: 'Mechanical Keyboard',
    title: 'Mechanical Keyboard',
    desc: 'RGB backlit mechanical keyboard',
    slug: 'mechanical-keyboard',
    longDesc:
      'Responsive keys, durable build, and customizable lighting effects.',
    price: 4500,
    category: 'Gaming',
  },
  {
    id: 10,
    image: '/Images/Product9.webp',
    alt: 'Monitor',
    title: '27-inch Gaming Monitor',
    desc: '144Hz refresh rate monitor',
    slug: 'gaming-monitor-27',
    longDesc:
      'Smooth visuals with high refresh rate, perfect for gamers and designers.',
    price: 22000,
    category: 'Gaming',
  },
];

const AllProducts = [
  ...RecentProducts,
  ...FeatureProducts,
  {
    id: 11,
    image: '/Images/Product10.webp',
    alt: 'Powerbank',
    title: '10,000mAh Powerbank',
    desc: 'Portable powerbank with fast charging',
    slug: '10000mah-powerbank',
    longDesc:
      'Stay charged on the go with this slim and lightweight powerbank.',
    price: 2000,
    category: 'Electronics',
  },
  {
    id: 12,
    image: '/Images/Product11.jpg',
    alt: 'WiFi Router',
    title: 'Dual Band WiFi Router',
    desc: 'High-speed WiFi router',
    slug: 'dual-band-router',
    longDesc: 'Reliable and fast WiFi connection with wide coverage.',
    price: 5500,
    category: 'Electronics',
  },
  {
    id: 13,
    image: '/Images/Product12.jpg',
    alt: 'Microphone',
    title: 'Studio Microphone',
    desc: 'Professional condenser microphone',
    slug: 'studio-microphone',
    longDesc: 'Perfect for podcasting, recording, and streaming.',
    price: 8000,
    category: 'Electronics',
  },
  {
    id: 14,
    image: '/Images/Product13.jpg',
    alt: 'Laptop Cooler',
    title: 'Laptop Cooling Pad',
    desc: 'Keep your laptop cool',
    slug: 'laptop-cooling-pad',
    longDesc:
      'Silent fans with LED lights to prevent overheating during long sessions.',
    price: 1800,
    category: 'Laptop',
  },
  {
    id: 15,
    image: '/Images/Product14.jpg',
    alt: 'Drone',
    title: 'Mini Camera Drone',
    desc: 'Foldable drone with HD camera',
    slug: 'mini-camera-drone',
    longDesc: 'Capture stunning aerial shots with easy controls.',
    price: 15000,
    category: 'Drone',
  },
  {
    id: 16,
    image: '/Images/Product15.avif',
    alt: 'VR Headset',
    title: 'VR Headset',
    desc: 'Immersive virtual reality headset',
    slug: 'vr-headset',
    longDesc:
      'Step into the virtual world with 360-degree view and comfortable design.',
    price: 12000,
    category: 'Gaming',
  },
  {
    id: 17,
    image: '/Images/Product16.jpg',
    alt: 'Graphic Card',
    title: 'NVIDIA RTX Graphics Card',
    desc: 'High performance for gaming & editing',
    slug: 'rtx-graphics-card',
    longDesc: 'Smooth rendering, ray tracing, and high FPS gaming experience.',
    price: 75000,
    category: 'Gaming',
  },
  {
    id: 18,
    image: '/Images/Product18.webp',
    alt: 'Tablet',
    title: 'Android Tablet',
    desc: '10-inch android tablet',
    slug: 'android-tablet',
    longDesc: 'Portable tablet with large screen and strong battery.',
    price: 25000,
    category: 'Electronics',
  },
  {
    id: 19,
    alt: 'Home Speaker',
    image: '/Images/Product19.jpg',
    title: 'Home Theater Speaker',
    desc: 'Surround sound speaker system',
    slug: 'home-theater-speaker',
    longDesc: 'Enhance your movie nights with booming sound and deep bass.',
    price: 40000,
    category: 'Speaker',
  },
  {
    id: 20,
    image: '/Images/Product20.jpg',
    alt: 'PS5 Controller',
    title: 'PS5 DualSense Controller',
    desc: 'Next-gen PS5 wireless controller',
    slug: 'ps5-controller',
    longDesc:
      'Adaptive triggers, haptic feedback, and sleek design for ultimate gaming.',
    price: 12000,
    category: 'Gaming',
  },
];

export { RecentProducts, FeatureProducts, AllProducts };
